### ISSUE TITLE
Script prompts twice when overriding default setting.

### ISSUE THREAD

**Issue by wileyfuller** [AllTheDucks/atd-b2-stub#10]
on branch [freemarker-template-config](/AllTheDucks/atd-b2-stub/tree/feature/freemarker-template-config)

When defaults have been set, and you want to use a value that's different to the default, the script prompts twice. e.g. 

```
Defaults found for generating building block
> Building 0% > :initB2
What is your Vendor Id (e.g. usq, unsw, qut, swin, etc)? [atd] atd

What is your Vendor Id (e.g. usq, unsw, qut, swin, etc)? atd
What is your Vendor Name (e.g. University of Antarctica)? [All the Ducks Pty Ltd]
```

**Comment by hscells** [comment]
This is resolved in pull request #9
